version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          path: main.tf
      - terraform/validate:
          checkout: true
          path: main.tf
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          path: main.tf
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          path: main.tf
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
